server:
  port: 8080

spring:
  application:
    name: "FloridaTripPlanner"
  datasource:
    url: jdbc:mysql://localhost:3560/floridaplanner
    username: root
    password: rootpassword
  jpa:
    show-sql: true
  sql:
    init:
      mode: always


logging:
  level:
    root: DEBUG


application1:
  update: " welcome to the prod env of the florida planner"